databases:
  - name: navya-db
    databaseName: navya_db
    user: navya_user
    plan: free

services:
  - type: web
    name: navya-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --workers 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: navya-db
          property: connectionString

  # - type: web
  #   name: navya-frontend
  #   env: static
  #   buildCommand: npm install --prefix frontend && npm run build --prefix frontend
  #   publishDir: frontend/build
  #   envVars:
  #     - key: REACT_APP_API_URL
  #       fromService:
  #         type: web
  #         name: navya-backend
  #         property: url # <--- Changed from 'host' to 'url'